config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:show, :create, :destroy]
  resource :user, only: [:show] do
    get :delayed, to: 'users#show_delayed'
  end

  namespace :api do
    resources :users, only: [:show], param: :name, defaults: { format: :json }
  end

  namespace :admin do
    resources :users, only: [:index, :new, :create]
  end
end

app/models/login_form.rb
class LoginForm
  include ActiveModel::Model

  attr_accessor :name
  attr_reader :login_user_id

  def login
    user = User.find_by(name: name)
    if user.present?
      @login_user_id = user.id
      true
    else
      errors.add(:name, 'is invalid')
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,
    presence: true,
    uniqueness: true

  validates :email,
    presence: true

  def name_with_email
    "#{name} <#{email}>"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < SecureApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email))
    if @user.save
      redirect_to action: :index
    else
      render :new
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  # GET /api/users/:name
  def show
    user = User.find_by!(name: params[:name])
    render json: user.attributes.slice("name", "email")
  rescue ActiveRecord::RecordNotFound
    render json: {}, status: :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private def current_user_id
    session[:user_id]
  end
end

app/controllers/secure_application_controller.rb
class SecureApplicationController < ApplicationController
  class Unauthorized < StandardError ; end

  before_action do
    if current_user_id.blank?
      raise Unauthorized
    end
  end

  rescue_from Unauthorized do
    render plain: '401 Unauthorized', status: 401
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
    @logged_in = current_user_id.present?
    @login_form = LoginForm.new
  end

  def create
    @login_form = LoginForm.new(params.require(:login_form).permit(:name))
    if @login_form.login
      session[:user_id] = @login_form.login_user_id
      redirect_to user_path
    else
      render :show
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to action: :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /user
  def show
  end

  def show_delayed
    @user = current_user_id.presence.try do |id|
      User.find(id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.erb
<div class="container shadow p-4">
  <% if user.errors.present? %>
    <div class="alert alert-danger" role="alert">
      <% user.errors.full_messages.each do |message| %>
        <%= content_tag :li, message %>
      <% end %> 
    </div>
  <% end %>
  <%= form_for [:admin, user] do |f| %>
    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'Email' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit 'Signup', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<div class="container p-4">
  <ul class="list-group">
    <% @users.each do |user| %>
        <%= content_tag :li, user.name, class: 'list-group-item' %>
    <% end %>
  </ul>
  <%= link_to "Add", new_admin_user_path, class: 'btn btn-primary' %>
</div>

app/views/admin/users/new.html.erb
<%= render 'form', user: @user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

app/views/users/show.html.erb
<h1>Current User</h1>
<div id="user_container">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>
<script type="text/javascript">
document.addEventListener("DOMContentLoaded", function(evt) {
  fetch('user/delayed').then(response => response.text()).then(html => {
    const container = document.getElementById("user_container");
    container.innerHTML = html;
  });
}, false);
</script>

app/views/users/show_delayed.html.erb
<div class="card shadow d-inline-flex">
  <div class="card-body">
    <% if @user.present? %>
      <h2 class="card-title">User ID: <%= @user.id %></h2>
      <h3 class="card-subtitle mb-2 text-muted"><%= @user.name %></h3>
      <%= link_to 'Logout', session_path, class: 'btn btn-primary', method: :delete %>
    <% else %>
      <h2 class="card-title">Not logged in.</h2>
      <%= link_to 'Login', session_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>